# This is the configuration for goreleaser
# Check the documentation at http://goreleaser.com for details
before:
  hooks:
    - go mod tidy
builds:
  -
    main: ./cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
    ignore:
      - goos: windows
        goarch: arm
gomod:
  proxy: true
archives:
  -
    name_template: >-
      ecs-ami-deploy_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-dev"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
