service: ecs-ami-deploy

frameworkVersion: '2'
configValidationMode: warn

provider:
  name: aws
  runtime: go1.x
  versionFunctions: false
  timeout: 900
  logRetentionInDays: 14

  environment:
    stage: ${self:custom.stage}

  stackTags:
    app: ${self:service}
    app_env: ${opt:stage, self:provider.stage}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

custom:
  stage: ${opt:stage, self:provider.stage}
  namespace: ${self:service}_${self:custom.stage}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  weekly:
    handler: bin/ead
    timeout: 900
    events:
      - schedule: cron(0 1 ? * SAT *) # every Saturday at 1am UTC
      - sns:
          topicName: